// src/use-cases/construction-fabrication/construction-fabrication.react.tsx
import React, { useEffect, useRef } from 'react';
import { mountConstructionFabricationWorkspace } from './construction-fabrication.workspace';
export default function ConstructionFabricationGanttDemo() { const host = useRef<HTMLDivElement>(null); useEffect(() => host.current ? mountConstructionFabricationWorkspace(host.current) : undefined, []); return <div ref={host} />; }

// src/use-cases/construction-fabrication/construction-fabrication.vue
<template><div ref="host" /></template>
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue';
import { mountConstructionFabricationWorkspace } from './construction-fabrication.workspace';
const host = ref<HTMLElement>(); let dispose: (() => void) | undefined;
onMounted(() => { if (host.value) dispose = mountConstructionFabricationWorkspace(host.value); }); onBeforeUnmount(() => dispose?.());
</script>
