// src/examples/horizontal-big-data/gantt-horizontal-big-data.react.tsx
import './gantt-horizontal-big-data.scss';
import React, { useEffect, useMemo, useState } from 'react';
import { RevoGrid } from '@revolist/react-datagrid';
import { GanttPlugin, createDefaultTaskTableColumn } from '@revolist/revogrid-enterprise';
import { currentTheme, observeCurrentTheme } from '../../theme';
import {
  createGanttHorizontalBigDataSet,
  ganttHorizontalBigDataCalendars,
  ganttHorizontalBigDataConfig,
} from './gantt-horizontal-big-data-data';

export default function GanttHorizontalBigData(_props: { rows?: any[] }) {
  const [isDark, setIsDark] = useState(() => currentTheme().isDark());
  const data = useMemo(() => createGanttHorizontalBigDataSet(), []);
  const plugins = useMemo(() => [GanttPlugin], []);
  const source = useMemo(() => data.tasks, [data.tasks]);
  const columns = useMemo(() => [createDefaultTaskTableColumn('name')], []);
  const gantt = useMemo(() => ganttHorizontalBigDataConfig, []);
  const dependencies = useMemo(() => data.dependencies, [data.dependencies]);
  const calendars = useMemo(() => ganttHorizontalBigDataCalendars, []);

  useEffect(() => observeCurrentTheme(setIsDark), []);

  return (
    <section className="gantt-horizontal-big-data-demo">
      <RevoGrid
        className="gantt-horizontal-big-data-grid"
        hideAttribution
        theme={isDark ? 'darkCompact' : 'compact'}
        plugins={plugins}
        source={source}
        columns={columns}
        gantt={gantt}
        ganttDependencies={dependencies}
        ganttCalendars={calendars}
      />
    </section>
  );
}

// src/examples/horizontal-big-data/gantt-horizontal-big-data.vue
<template>
  <section class="gantt-horizontal-big-data-demo">
    <RevoGrid
      class="gantt-horizontal-big-data-grid"
      hide-attribution
      :theme="isDark ? 'darkCompact' : 'compact'"
      :plugins="plugins"
      :source="rows"
      :columns="columns"
      :gantt.prop="ganttConfig"
      :gantt-dependencies.prop="dependencies"
      :gantt-calendars.prop="calendars"
    />
  </section>
</template>

<script setup lang="ts">
import { onBeforeUnmount, ref } from 'vue';
import RevoGrid from '@revolist/vue3-datagrid';
import { GanttPlugin, createDefaultTaskTableColumn } from '@revolist/revogrid-enterprise';
import { currentTheme, observeCurrentTheme } from '../../theme';
import {
  createGanttHorizontalBigDataSet,
  ganttHorizontalBigDataCalendars,
  ganttHorizontalBigDataConfig,
} from './gantt-horizontal-big-data-data';

const plugins = [GanttPlugin];
const data = createGanttHorizontalBigDataSet();
const rows = ref(data.tasks);
const dependencies = ref(data.dependencies);
const columns = ref([createDefaultTaskTableColumn('name')]);
const ganttConfig = ref(ganttHorizontalBigDataConfig);
const calendars = ref(ganttHorizontalBigDataCalendars);
const isDark = ref(currentTheme().isDark());
const disconnectTheme = observeCurrentTheme((value) => {
  isDark.value = value;
});

onBeforeUnmount(disconnectTheme);
</script>

<style src="./gantt-horizontal-big-data.scss" lang="scss"></style>
