// src/use-cases/professional-services/professional-services.react.tsx
import '../shared/industry-use-case.scss';
import './professional-services.presentation.scss';
import React, { useEffect, useMemo, useState } from 'react';
import { RevoGrid } from '@revolist/react-datagrid';
import { currentTheme, observeCurrentTheme } from '../../theme';
import { PROFESSIONAL_SERVICES_INDUSTRY_DEFINITION as definition } from './professional-services.data';
import { createIndustryGanttConfig } from '../shared/industry-use-case.types';
import {
  industryGridClass,
  industryGridTheme,
  industryPlugins,
  industryShellClass,
} from '../shared/industry-use-case.shared';

const EnterpriseRevoGrid = RevoGrid as React.ComponentType<any>;

export default function ProfessionalServicesGanttDemo() {
  const [dark, setDark] = useState(() => currentTheme().isDark());
  const [showBaseline, setShowBaseline] = useState(false);
  const [showCriticalPath, setShowCriticalPath] = useState(true);
  const plugins = useMemo(() => industryPlugins(definition), []);
  const columns = useMemo(() => [...definition.columns], []);
  const source = useMemo(() => [...definition.tasks], []);
  const dependencies = useMemo(() => [...definition.dependencies], []);
  const calendars = useMemo(() => [...definition.calendars], []);
  const resources = useMemo(() => [...definition.resources], []);
  const assignments = useMemo(() => [...definition.assignments], []);
  const baselines = useMemo(() => [...definition.baselines], []);
  const gantt = useMemo(
    () => createIndustryGanttConfig(definition, showBaseline, showCriticalPath),
    [showBaseline, showCriticalPath],
  );

  useEffect(() => observeCurrentTheme(setDark), []);

  return (
    <section className={industryShellClass(dark, definition.id)} aria-label={`${definition.productLabel} ${definition.title}`}>
      <header className="industry-gantt-header">
        <div className="industry-gantt-identity">
          <span className="industry-gantt-mark">{definition.mark}</span>
          <div>
            <div className="industry-gantt-product">{definition.productLabel}</div>
            <h1 className="industry-gantt-title">{definition.title}</h1>
            <p className="industry-gantt-subtitle">{definition.subtitle}</p>
          </div>
        </div>
        <div className="industry-gantt-metrics">
          {definition.metrics.map((metric) => (
            <div key={metric.label} className={`industry-gantt-metric industry-gantt-metric--${metric.tone ?? 'default'}`}>
              <strong className="industry-gantt-metric__value">{metric.value}</strong>
              <span className="industry-gantt-metric__label">{metric.label}</span>
            </div>
          ))}
        </div>
        <div className="industry-gantt-sync"><span className="industry-gantt-sync__dot" />{definition.updatedLabel}</div>
      </header>
      <div className="industry-gantt-toolbar">
        <span className="industry-gantt-toolbar__label">{definition.scheduleLabel}</span>
        <span className="industry-gantt-toolbar__legend">{definition.riskLegendLabel}</span>
        <button type="button" className="industry-gantt-toggle" aria-pressed={showBaseline} onClick={() => setShowBaseline((value) => !value)}>Baseline</button>
        <button type="button" className="industry-gantt-toggle" aria-pressed={showCriticalPath} onClick={() => setShowCriticalPath((value) => !value)}>Critical path</button>
      </div>
      <EnterpriseRevoGrid
        className={industryGridClass(definition)}
        theme={industryGridTheme(definition, dark)}
        hideAttribution
        readonly={false}
        range
        resize
        rowSize={definition.grid?.rowSize ?? 34}
        rowHeaders={definition.grid?.rowHeaders ?? false}
        autoSizeColumn={false}
        plugins={plugins}
        columns={columns}
        source={source}
        gantt={gantt}
        ganttDependencies={dependencies}
        ganttCalendars={calendars}
        ganttResources={resources}
        ganttAssignments={assignments}
        ganttBaselines={baselines}
      />
    </section>
  );
}

// src/use-cases/professional-services/professional-services.vue
<template>
  <section :class="shellClass" :aria-label="`${definition.productLabel} ${definition.title}`">
    <header class="industry-gantt-header">
      <div class="industry-gantt-identity">
        <span class="industry-gantt-mark">{{ definition.mark }}</span>
        <div>
          <div class="industry-gantt-product">{{ definition.productLabel }}</div>
          <h1 class="industry-gantt-title">{{ definition.title }}</h1>
          <p class="industry-gantt-subtitle">{{ definition.subtitle }}</p>
        </div>
      </div>
      <div class="industry-gantt-metrics">
        <div v-for="metric in definition.metrics" :key="metric.label" :class="`industry-gantt-metric industry-gantt-metric--${metric.tone ?? 'default'}`">
          <strong class="industry-gantt-metric__value">{{ metric.value }}</strong>
          <span class="industry-gantt-metric__label">{{ metric.label }}</span>
        </div>
      </div>
      <div class="industry-gantt-sync"><span class="industry-gantt-sync__dot" />{{ definition.updatedLabel }}</div>
    </header>
    <div class="industry-gantt-toolbar">
      <span class="industry-gantt-toolbar__label">{{ definition.scheduleLabel }}</span>
      <span class="industry-gantt-toolbar__legend">{{ definition.riskLegendLabel }}</span>
      <button type="button" class="industry-gantt-toggle" :aria-pressed="showBaseline" @click="showBaseline = !showBaseline">Baseline</button>
      <button type="button" class="industry-gantt-toggle" :aria-pressed="showCriticalPath" @click="showCriticalPath = !showCriticalPath">Critical path</button>
    </div>
    <RevoGrid
      :class="gridClass"
      :theme="theme"
      hide-attribution
      :readonly="false"
      :range="true"
      :resize="true"
      :row-size="definition.grid?.rowSize ?? 34"
      :row-headers="definition.grid?.rowHeaders ?? false"
      :auto-size-column="false"
      :plugins="plugins"
      :columns="columns"
      :source="source"
      :gantt.prop="gantt"
      :gantt-dependencies.prop="dependencies"
      :gantt-calendars.prop="calendars"
      :gantt-resources.prop="resources"
      :gantt-assignments.prop="assignments"
      :gantt-baselines.prop="baselines"
    />
  </section>
</template>

<script setup lang="ts">
import '../shared/industry-use-case.scss';
import './professional-services.presentation.scss';
import { computed, onBeforeUnmount, ref } from 'vue';
import RevoGrid from '@revolist/vue3-datagrid';
import { currentTheme, observeCurrentTheme } from '../../theme';
import { PROFESSIONAL_SERVICES_INDUSTRY_DEFINITION as definition } from './professional-services.data';
import { createIndustryGanttConfig } from '../shared/industry-use-case.types';
import {
  industryGridClass,
  industryGridTheme,
  industryPlugins,
  industryShellClass,
} from '../shared/industry-use-case.shared';

const plugins = industryPlugins(definition);
const columns = [...definition.columns];
const source = ref([...definition.tasks]);
const dependencies = [...definition.dependencies];
const calendars = [...definition.calendars];
const resources = [...definition.resources];
const assignments = [...definition.assignments];
const baselines = [...definition.baselines];
const showBaseline = ref(false);
const showCriticalPath = ref(true);
const gantt = computed(() => createIndustryGanttConfig(definition, showBaseline.value, showCriticalPath.value));
const dark = ref(currentTheme().isDark());
const theme = computed(() => industryGridTheme(definition, dark.value));
const gridClass = industryGridClass(definition);
const shellClass = computed(() => industryShellClass(dark.value, definition.id));
const disconnectTheme = observeCurrentTheme((value) => {
  dark.value = value;
});
onBeforeUnmount(disconnectTheme);
</script>
